feat(golang): add table scaleway_iam_api_key
turbot/steampipe-plugin-scaleway pull request #25
Opened 2023-03-16 13:48 UTC by jplanckeel

# Describe

We add a table to list API Key and list users.  

API to list iam_apikey need organization_id, for this we add in config file organization_id. We have no other way to get this id.

# Example query results
<details>
  <summary>Results</summary>
  
```
select
  access_key,
  created_at,
  user_id,
  expires_at,
  default_project_id
from
  scaleway_iam_api_key
```

iam user 

```
select
  email,
  created_at,
  last_login_at,
  id,
  status,
  two_factor_enabled
from
  scaleway_iam_user
```
</details>

2023-03-24 08:32 UTC, francois2metz commented on config/scaleway.spc
> +  organization_id = "YOUR_ORGANIZATION_ID"
Could you describe how to get the organization id?

2023-03-24 08:32 UTC, francois2metz commented on go.sum
> +github.com/scaleway/scaleway-sdk-go v1.0.0-beta.14/go.mod h1:fCa7OJZ/9DRTnOKmxvT6pn+LPWUptQAmHF/SBJUGEcg=
Could you run `go mod tidy` to cleanup previous releases from the `go.sum`

2023-03-29 02:47 UTC, cbruno10 commented
@jplanckeel Sorry for the delay in review, I should get a chance later this week!

2023-06-01 08:14 UTC, jplanckeel commented
Hi, no problem. I check this MR today to test/update with new version of steampipe ;)

2023-06-05 15:27 UTC, cbruno10 requested changes
@jplanckeel Please see review comments, thanks!

2023-06-05 15:27 UTC, cbruno10 commented on scaleway/service.go
> +	if scalewayConfig.OrganizationID == nil {
@jplanckeel What Scaleway resources require this organization ID beside users and API keys? Do any of the existing tables require it?

Up until now, we haven't had any tables that required it, so adding it in now as a required config arg would be a breaking change, i.e., anyone who uses the Scaleway plugin today would suddenly be unable to until they added the `organization_id` config arg.

In some plugins, we add optional config args and then note in the appropriate table docs which optional config args are required, e.g., https://hub.steampipe.io/plugins/turbot/hibp#configuration and https://hub.steampipe.io/plugins/turbot/hibp/tables/hibp_paste.

2023-06-05 15:27 UTC, cbruno10 commented
@jplanckeel Sorry for the extremely long response time, I've added some questions around the new organization ID config arg, can you please have a look when you get a chance? Thanks!

2023-07-27 05:59 UTC, merged